server:
  servlet:
    context-path: /my-app
  port: 8080
spring:
  kafka:
    bootstrapAddress: localhost:9090
    groupId: group1
    groupId2: group2
    groupId3: group3
    topic: match_topic
    topic2: team_topic
    topic3: match_result_topic
    application:
    name: football

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432}/${DATABASE_NAME:football}
    username: ${DATABASE_USERNAME:user}
    driver-class-name: org.postgresql.Driver
    password: ${DATABASE_PASSWORD:user}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
app:
  kafka:
    enabled: false

format:
  date: yyyy-MM-dd HH:mm
