spring:
  datasource:
    username: sa
    password: 123
    url: jdbc:h2:mem:footballApp
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: true
  liquibase:
    enabled: false
    change-log: db/changelog/db.changelog-master.xml