insert into team (id, name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Arsenal-test', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Bournemouth', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Brighton & Hove Albion', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Burnley', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Chelsea', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Crystal Palace', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Everton', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Huddersfield Town', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Leicester City', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Liverpool', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Manchester City', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Manchester United', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Newcastle United', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Southampton', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Stoke City', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Swansea City', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Tottenham Hotspur', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'Watford', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'West Bromwich Albion', 0, 0, 0, 0, 0);
insert into team (id,name, number_of_games, other_points, points, scip_goals, total_goals) values (random_uuid(),'West Ham United', 0, 0, 0, 0, 0);
